# Generated by Django 4.1.7 on 2023-04-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(max_length=2)),
                ('phone', models.IntegerField(max_length=10)),
                ('Details', models.TextField()),
                ('visitdate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
