# Generated by Django 4.1.7 on 2023-05-05 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
