# Generated by Django 4.1.7 on 2023-05-05 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='completed',
        ),
    ]
