# Generated by Django 4.1.7 on 2023-05-05 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_rename_status_order_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='completed',
            new_name='status',
        ),
    ]
