# Generated by Django 4.1.7 on 2023-05-05 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_remove_order_status_order_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='completed',
        ),
    ]
